
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Step from './components/step'
import Step2 from '../pages/components/step2'
import Step3 from '../pages/components/step3'
import Step4 from '../pages/components/step4'
import Step5 from '../pages/components/step5'
import Logore from '../public/Logore.svg'
import Buttonregis from '../pages/components/buttonregis'
import Registration from '../pages/components/registrasi'





import Foot from '../pages/components/wave'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>UUID</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </Head>
      <div className='mt-6 ml-6'>
      <Logore />
      </div>
   
       <main className="size-users mx-auto w-full py-8  ">
       <Step />
  
       <Registration />
     </main>
 

    </>
  )
}
